import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { Menu, ArrowLeft, Download } from "lucide-react";
import { Logo, LogoMark } from "@/components/brand/Logo";
import { GOLD, NAVY, OFF_WHITE, TAGLINE, TEAL, TEAL_BRIGHT, TEAL_DEEP } from "@/lib/brand";

/**
 * Internal brand reference for the PayBridge identity.
 *
 * Shows the lockups, the mark, the two-colour palette and the type system
 * across the contexts they must survive: header, app icon, favicon sizes,
 * social avatar, navy and white grounds, and single-colour use.
 */
function Tile({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="flex flex-col gap-3">
      <span className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
        {label}
      </span>
      <div className="flex flex-1 items-center justify-center rounded-2xl border border-border bg-card/60 p-6">
        {children}
      </div>
    </div>
  );
}

function Swatch({
  name,
  hex,
  note,
  textClass,
}: {
  name: string;
  hex: string;
  note: string;
  textClass: string;
}) {
  return (
    <div className="overflow-hidden rounded-2xl border border-border">
      <div className="flex h-28 items-end p-4" style={{ backgroundColor: hex }}>
        <span className={`font-display text-sm font-bold ${textClass}`}>{name}</span>
      </div>
      <div className="bg-card p-4">
        <p className="font-mono text-sm font-semibold uppercase text-foreground">{hex}</p>
        <p className="mt-1 text-sm text-muted-foreground">{note}</p>
      </div>
    </div>
  );
}

/* The download pack, generated by scripts/build-brand.mjs into public/brand/.
   Each entry ships as both a PNG (2400px) and an SVG master. `ground` is only
   the preview swatch's background — the transparent files really are
   transparent, so the preview shows a checker instead. */
const DOWNLOADS = [
  {
    file: "paybridge-logo-tagline-on-light",
    label: "Primary lockup · on light",
    note: "The full lockup with the tagline. The default for documents and decks.",
    ground: OFF_WHITE,
  },
  {
    file: "paybridge-logo-tagline-on-dark",
    label: "Primary lockup · on dark",
    note: "The same lockup reversed on navy ink.",
    ground: NAVY,
  },
  {
    file: "paybridge-logo-tagline-navy",
    label: "Primary lockup · transparent, navy ink",
    note: "For placing on a light surface you already control.",
    ground: null,
  },
  {
    file: "paybridge-logo-tagline-white",
    label: "Primary lockup · transparent, white ink",
    note: "For placing on a dark surface or a photograph.",
    ground: NAVY,
  },
  {
    file: "paybridge-logo-on-light",
    label: "Horizontal · no tagline",
    note: "Headers, app bars and anywhere under about 40px tall.",
    ground: OFF_WHITE,
  },
  {
    file: "paybridge-logo-on-dark",
    label: "Horizontal · no tagline, on dark",
    note: "The same, reversed.",
    ground: NAVY,
  },
  {
    file: "paybridge-mark-navy",
    label: "Mark only · navy uprights",
    note: "Avatars, stamps and favicons. Transparent.",
    ground: OFF_WHITE,
  },
  {
    file: "paybridge-mark-white",
    label: "Mark only · white uprights",
    note: "The same on a dark ground. Transparent.",
    ground: NAVY,
  },
] as const;

function DownloadCard({
  file,
  label,
  note,
  ground,
}: {
  file: string;
  label: string;
  note: string;
  ground: string | null;
}) {
  return (
    <div className="flex flex-col overflow-hidden rounded-2xl border border-border bg-card/60">
      <div
        className="flex h-32 items-center justify-center p-5"
        style={ground ? { backgroundColor: ground } : undefined}
      >
        <img
          src={`/brand/${file}.svg`}
          alt={label}
          className="max-h-full max-w-full object-contain"
        />
      </div>
      <div className="flex flex-1 flex-col p-4">
        <p className="font-display text-sm font-bold text-foreground">{label}</p>
        <p className="mt-1 flex-1 text-sm text-muted-foreground">{note}</p>
        <div className="mt-4 flex gap-2">
          <a
            href={`/brand/${file}.png`}
            download
            className="inline-flex min-h-[40px] flex-1 items-center justify-center gap-2 rounded-full btn-brand px-4 text-sm font-semibold transition-transform duration-200 hover:-translate-y-0.5"
          >
            <Download className="h-4 w-4" /> PNG
          </a>
          <a
            href={`/brand/${file}.svg`}
            download
            className="inline-flex min-h-[40px] flex-1 items-center justify-center gap-2 rounded-full border border-border px-4 text-sm font-semibold text-foreground/80 transition-colors hover:border-primary/50 hover:text-primary"
          >
            <Download className="h-4 w-4" /> SVG
          </a>
        </div>
      </div>
    </div>
  );
}

export default function Brand() {
  return (
    <div className="min-h-screen bg-background px-5 py-16 text-foreground md:px-8">
      <div className="mx-auto max-w-5xl">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
        >
          <ArrowLeft className="h-4 w-4" /> Back to site
        </Link>

        <h1 className="mt-6 font-display text-4xl font-extrabold tracking-tight sm:text-5xl">
          Brand identity
        </h1>
        <p className="mt-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
          A tapered teal span arcing over three uprights, and a wordmark built on weight
          contrast — light <span className="font-light">Pay</span>, heavy{" "}
          <span className="font-extrabold">Bridge</span>. Deep navy is the ground; emerald teal is
          the accent, with gold kept for the far bank. {TAGLINE}
        </p>

        {/* Primary lockup */}
        <section className="mt-12">
          <h2 className="font-display text-2xl font-bold">Lockups</h2>
          <div className="mt-6 grid gap-6 sm:grid-cols-2">
            <Tile label="1 · Primary — with tagline">
              <Logo className="h-20" withTagline />
            </Tile>
            <Tile label="2 · Horizontal — no tagline">
              <Logo className="h-12" />
            </Tile>
            <Tile label="3 · Mark only">
              <LogoMark className="h-auto w-32" />
            </Tile>
            <Tile label="4 · Reverse on navy">
              <div
                className="flex h-28 w-full items-center justify-center rounded-xl"
                style={{ backgroundColor: NAVY, color: OFF_WHITE }}
              >
                <Logo className="h-16" withTagline />
              </div>
            </Tile>
          </div>
        </section>

        {/* Downloads */}
        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold">Download</h2>
          <p className="mt-2 max-w-2xl text-muted-foreground">
            Ready-made files with the clear space already built in. PNG is 2400px wide — enough for
            a full-bleed slide or a letterhead at print resolution. Use the SVG wherever it is
            accepted: it is the master and it never softens.
          </p>
          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            {DOWNLOADS.map((d) => (
              <DownloadCard key={d.file} {...d} />
            ))}
          </div>
        </section>

        {/* Palette */}
        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold">Colour</h2>
          <p className="mt-2 max-w-2xl text-muted-foreground">
            Navy ground, three depths of teal, one gold. The teals all sit on hue 165, so they read
            as one colour at three distances rather than three decisions — deep is weight, emerald
            is identity, bright is outcome. Gold is the deliberate opposite pole and the only warm
            hue in the system. Teal is the mechanism; gold is the result. That split is the
            tagline, made visible.
          </p>
          <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
            <Swatch
              name="Navy Ink"
              hex={NAVY}
              note="Ground. Backgrounds and surfaces."
              textClass="text-white"
            />
            <Swatch
              name="Deep Teal"
              hex={TEAL_DEEP}
              note="Tone one. Weight, gradient anchors, dark blocks."
              textClass="text-white"
            />
            <Swatch
              name="Emerald Teal"
              hex={TEAL}
              note="Tone two. The span, primary actions, links."
              textClass="text-[#091320]"
            />
            <Swatch
              name="Bright Teal"
              hex={TEAL_BRIGHT}
              note="Tone three. Available pay, verified, settled, cleared."
              textClass="text-[#091320]"
            />
            <Swatch
              name="Gold"
              hex={GOLD}
              note="The far bank. Prosperity, attention, still building."
              textClass="text-[#091320]"
            />
            <Swatch
              name="Warm White"
              hex={OFF_WHITE}
              note="Reverse type and marks on ink."
              textClass="text-[#091320]"
            />
          </div>

          <div className="mt-6 grid gap-6 lg:grid-cols-2">
            <div className="overflow-hidden rounded-2xl border border-border">
              <div className="bg-prosperity h-16" />
              <div className="bg-card p-4">
                <p className="font-display text-sm font-bold">Payroll → prosperity ramp</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  Deep teal at the near bank, emerald mid-span, gold at the far one. For spans,
                  meters and progress — anything that represents crossing. Never a flat background.
                </p>
              </div>
            </div>
            <div className="overflow-hidden rounded-2xl border border-border">
              <div className="bg-twotone h-16" />
              <div className="bg-card p-4">
                <p className="font-display text-sm font-bold">Two-tone teal</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  The teals alone, for surfaces that need weight and a lit edge but make no claim
                  about an outcome. Headers, feature panels, the app shell.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Typography */}
        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold">Typography</h2>
          <div className="mt-6 grid gap-6 sm:grid-cols-2">
            <div className="rounded-2xl border border-border bg-card/60 p-6">
              <p className="font-display text-6xl font-extrabold leading-none">Aa</p>
              <p className="mt-4 font-display text-lg font-bold">Inter</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Wordmark and all headings. Tightened tracking. Clean, modern, confident.
              </p>
            </div>
            <div className="rounded-2xl border border-border bg-card/60 p-6">
              <p className="font-sans text-6xl font-extrabold leading-none">Aa</p>
              <p className="mt-4 font-display text-lg font-bold">Manrope</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Body copy, interface labels and figures. Set money in tabular numerals.
              </p>
            </div>
          </div>
        </section>

        {/* Contexts */}
        <section className="mt-16">
          <h2 className="font-display text-2xl font-bold">In context</h2>
          <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <Tile label="Mobile header">
              <div
                className="flex w-full items-center justify-between rounded-xl px-4 py-3"
                style={{ backgroundColor: NAVY, color: OFF_WHITE }}
              >
                <Logo className="h-7" />
                <Menu className="h-5 w-5" />
              </div>
            </Tile>

            {/* The icons invert: a light tile with a navy deck, because a teal
                span on navy disappears at 32px. Sized by width, not height —
                the mark is about three and a half times wider than it is tall. */}
            <Tile label="App icon">
              <div
                className="flex h-24 w-24 items-center justify-center rounded-[22px] shadow-lg"
                style={{ backgroundColor: OFF_WHITE, color: NAVY }}
              >
                <LogoMark className="h-auto w-[76px]" />
              </div>
            </Tile>

            <Tile label="Social avatar">
              <div
                className="flex h-24 w-24 items-center justify-center rounded-full shadow-lg"
                style={{ backgroundColor: NAVY, color: OFF_WHITE }}
              >
                <LogoMark className="h-auto w-[66px]" />
              </div>
            </Tile>

            <Tile label="Favicon · 32 / 16 px">
              <div className="flex items-end gap-4">
                <div
                  className="flex h-8 w-8 items-center justify-center rounded-md"
                  style={{ backgroundColor: OFF_WHITE, color: NAVY }}
                >
                  <LogoMark className="h-auto w-[25px]" />
                </div>
                <div
                  className="flex h-4 w-4 items-center justify-center rounded-sm"
                  style={{ backgroundColor: OFF_WHITE, color: NAVY }}
                >
                  <LogoMark className="h-auto w-[13px]" />
                </div>
              </div>
            </Tile>

            <Tile label="White ground">
              <div
                className="flex h-24 w-full items-center justify-center rounded-xl bg-white"
                style={{ color: NAVY }}
              >
                <Logo className="h-9" />
              </div>
            </Tile>

            <Tile label="Monochrome · one colour">
              <div
                className="flex h-24 w-full items-center justify-center rounded-xl bg-white"
                style={{ color: NAVY }}
              >
                <Logo className="h-9" monochrome />
              </div>
            </Tile>
          </div>
        </section>

        <section className="mt-16 rounded-2xl border border-border bg-card/60 p-6">
          <h2 className="font-display text-xl font-bold">Rules</h2>
          <ul className="mt-4 space-y-2 text-sm leading-relaxed text-muted-foreground">
            <li>· The span is always PayBridge Teal, or the single colour in monochrome use. Gold appears in the lockup only as the far tagline rule.</li>
            <li>· Bright teal means outcome, not decoration. If it is not settled, verified, cleared or available, it is not bright teal.</li>
            <li>· Gold is a trim: attention, shortfall, still building, and the far bank of the ramp. Never a surface, never a second brand colour.</li>
            <li>· Never recolour "Bridge" — the wordmark works on weight contrast, not colour contrast.</li>
            <li>· Clear space around the lockup: at least the height of the mark on every side.</li>
            <li>· Below 24px, use the mark alone. The wordmark stops being legible before the mark does.</li>
            <li>· On photography, place the reverse lockup on navy — never the mark straight onto an image.</li>
          </ul>
        </section>
      </div>
    </div>
  );
}
