import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, FileText } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, ActionButton } from "@/components/dashboard/PageHeader";
import { Panel, InfoNote } from "@/components/dashboard/Panel";
import { StatCard, StatGrid } from "@/components/dashboard/StatCard";
import { EmptyState, ErrorState, LoadingPanel } from "@/components/dashboard/states";
import { SelectField } from "@/components/dashboard/forms";
import { InvestorDisclosureLine } from "@/components/investor/Disclosures";
import { investorApi, qk } from "@/lib/platform/mock-service";
import { downloadCsv, downloadFile, naira, shortDate } from "@/lib/platform/format";
import type { Statement } from "@/lib/platform/models";
import { useAccountId } from "@/lib/platform/use-account";

const KINDS = ["All", "Statement", "Tax report", "Portfolio report"];

export default function InvestorStatementsPage() {
  const investorId = useAccountId("investor");
  const [kind, setKind] = useState(KINDS[0]);
  const [downloading, setDownloading] = useState<string | null>(null);

  const statements = useQuery({
    queryKey: qk.investorStatements(investorId),
    queryFn: () => investorApi.statements(investorId),
  });
  const overview = useQuery({
    queryKey: qk.investorOverview(investorId),
    queryFn: () => investorApi.overview(investorId),
  });
  const transactions = useQuery({
    queryKey: qk.investorTransactions(investorId),
    queryFn: () => investorApi.transactions(investorId),
  });

  const rows = (statements.data ?? []).filter((row) => kind === "All" || row.kind === kind);

  const download = async (statement: Statement) => {
    setDownloading(statement.id);
    await new Promise((resolve) => setTimeout(resolve, 900));
    downloadFile(
      `${statement.title.replace(/\s+/g, "-").toLowerCase()}.txt`,
      [
        "PayBridge — Investor document",
        `Document: ${statement.title}`,
        `Period: ${statement.period}`,
        `Generated: ${shortDate(statement.generatedAt)}`,
        `Portfolio value: ${naira(overview.data?.investor.portfolioValue ?? 0)}`,
        "",
        "Investment returns are not guaranteed. Past performance does not guarantee future results.",
        "This is a simulated document generated by the PayBridge prototype.",
      ].join("\n"),
    );
    setDownloading(null);
    toast.success(`${statement.title} downloaded`);
  };

  const exportTransactions = () => {
    const data = (transactions.data ?? []).map((row) => ({
      Reference: row.reference,
      Type: row.type,
      Date: shortDate(row.createdAt),
      Amount: row.amount,
      Fee: row.fee,
      Status: row.status,
    }));
    if (!data.length) {
      toast.info("There are no transactions to export yet");
      return;
    }
    downloadCsv("paybridge-investor-transactions.csv", data);
    toast.success("Transaction history exported");
  };

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Statements"
        title="Statements and tax documents"
        description="Portfolio statements, tax reports and transaction history for your records."
        actions={
          <ActionButton icon={<Download className="h-4 w-4" />} onClick={exportTransactions}>
            Export transactions
          </ActionButton>
        }
      />

      <StatGrid columns={3}>
        <StatCard label="Documents available" value={String((statements.data ?? []).length)} tone="primary" />
        <StatCard
          label="Portfolio value"
          value={naira(overview.data?.investor.portfolioValue ?? 0)}
          hint="As at today"
        />
        <StatCard
          label="Net income to date"
          value={naira(overview.data?.investor.netIncomeEarned ?? 0)}
          tone="protected"
        />
      </StatGrid>

      <Panel
        title="Your documents"
        description="Generated at the end of each period and kept for seven years."
        action={
          <div className="w-44">
            <SelectField
              label=""
              value={kind}
              onChange={setKind}
              options={KINDS.map((value) => ({ value, label: value }))}
            />
          </div>
        }
      >
        {statements.isLoading ? (
          <LoadingPanel />
        ) : statements.isError ? (
          <ErrorState onRetry={() => void statements.refetch()} />
        ) : rows.length === 0 ? (
          <EmptyState
            title="No documents in this view"
            body={
              kind === "All"
                ? "Your first statement is generated at the end of your first full period."
                : `No ${kind.toLowerCase()} documents yet. Try a different filter.`
            }
            icon={<FileText className="h-5 w-5" />}
            action={
              kind === "All" ? undefined : (
                <ActionButton variant="secondary" onClick={() => setKind("All")}>
                  Show all documents
                </ActionButton>
              )
            }
          />
        ) : (
          <ul className="space-y-2.5">
            {rows.map((statement) => (
              <li key={statement.id} className="flex items-center gap-3.5 rounded-2xl border border-border p-4">
                <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-muted-foreground">
                  <FileText className="h-4 w-4" />
                </span>
                <span className="min-w-0 flex-1">
                  <span className="block truncate text-sm font-semibold text-foreground">{statement.title}</span>
                  <span className="mt-0.5 block text-xs text-muted-foreground">
                    {statement.kind} · {statement.period} · {statement.sizeKb} KB
                  </span>
                </span>
                <ActionButton
                  size="sm"
                  variant="secondary"
                  loading={downloading === statement.id}
                  onClick={() => void download(statement)}
                >
                  Download
                </ActionButton>
              </li>
            ))}
          </ul>
        )}
        <InfoNote className="mt-4">
          Statements are prepared by the investment manager and reconciled against custodian records.
        </InfoNote>
      </Panel>

      <InvestorDisclosureLine />
    </div>
  );
}
