import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, FileText } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, ActionButton } from "@/components/dashboard/PageHeader";
import { Panel, InfoNote } from "@/components/dashboard/Panel";
import { StatCard, StatGrid } from "@/components/dashboard/StatCard";
import { ChartTabs, TrendChart, sliceSeries, useChartRange } from "@/components/dashboard/charts";
import { EmptyState, ErrorState, LoadingPanel } from "@/components/dashboard/states";
import { SelectField } from "@/components/dashboard/forms";
import { employerApi, qk } from "@/lib/platform/mock-service";
import { downloadCsv, downloadFile, naira, nairaCompact, shortDate } from "@/lib/platform/format";
import type { Statement } from "@/lib/platform/models";
import { useAccountId } from "@/lib/platform/use-account";

const PERIODS = ["This cycle", "Last 3 months", "Last 6 months", "Year to date"];

export default function EmployerReportsPage() {
  const employerId = useAccountId("employer");
  const range = useChartRange(["3M", "6M", "12M"]);
  const [period, setPeriod] = useState(PERIODS[1]);
  const [downloading, setDownloading] = useState<string | null>(null);

  const overview = useQuery({
    queryKey: qk.employerOverview(employerId),
    queryFn: () => employerApi.overview(employerId),
  });
  const reports = useQuery({
    queryKey: qk.employerReports(employerId),
    queryFn: () => employerApi.reports(employerId),
  });
  const activity = useQuery({
    queryKey: qk.employerActivity(employerId),
    queryFn: () => employerApi.bridgeActivity(employerId),
  });

  const download = async (statement: Statement) => {
    setDownloading(statement.id);
    await new Promise((resolve) => setTimeout(resolve, 900));
    downloadFile(
      `${statement.title.replace(/\s+/g, "-").toLowerCase()}.txt`,
      [
        "PayBridge — Employer report",
        `Report: ${statement.title}`,
        `Period: ${statement.period}`,
        `Generated: ${shortDate(statement.generatedAt)}`,
        "",
        "This is a simulated document generated by the PayBridge prototype.",
      ].join("\n"),
    );
    setDownloading(null);
    toast.success(`${statement.title} downloaded`);
  };

  const exportActivity = () => {
    /*
     * One row per payroll cycle, being the single figure to deduct and remit.
     *
     * This export previously wrote a named row per employee — "Employee",
     * "Employee reference", "Amount to deduct" — which put a permanent list of
     * who had used Bridge, and for how much, onto a finance team's shared drive.
     * A CSV is the worst possible place for that: it outlives the session, gets
     * emailed, and no access log follows it.
     */
    const rows = (activity.data?.settlements ?? []).map((row) => ({
      Period: row.period,
      Payday: shortDate(row.payday),
      Description: row.description,
      Reference: row.reference,
      "Total to deduct": row.totalToDeduct,
      "Employees included": row.employeesIncluded ?? "Fewer than 5 — withheld",
      Status: row.status,
    }));
    if (!rows.length) {
      toast.info("There is no activity to export yet");
      return;
    }
    downloadCsv("paybridge-payroll-deductions.csv", rows);
    toast.success("Payroll deduction schedule exported");
  };

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Reports"
        title="Reporting and downloads"
        description="Everything your finance team needs for reconciliation and audit."
        actions={
          <ActionButton icon={<Download className="h-4 w-4" />} onClick={exportActivity}>
            Export deduction schedule
          </ActionButton>
        }
      />

      {overview.isLoading ? (
        <LoadingPanel />
      ) : overview.isError ? (
        <ErrorState onRetry={() => void overview.refetch()} />
      ) : overview.data ? (
        <StatGrid columns={4}>
          <StatCard label="Payroll obligation" value={naira(overview.data.employer.payrollObligation)} />
          <StatCard
            label="Bridged this cycle"
            value={naira(activity.data?.summary.volumeThisCycle ?? 0)}
            tone="primary"
          />
          <StatCard
            label="Employees using Bridge"
            value={String(overview.data.employer.employeesUsingBridge)}
          />
          <StatCard label="Available reports" value={String((reports.data ?? []).length)} tone="protected" />
        </StatGrid>
      ) : null}

      <div className="grid gap-6 lg:grid-cols-[1.2fr_1fr]">
        <Panel
          title="Bridge volume"
          description="Use the filters to match your reporting period."
          action={<ChartTabs options={range.options} value={range.value} onChange={range.setValue} />}
        >
          {activity.isLoading ? (
            <LoadingPanel />
          ) : (
            <TrendChart data={sliceSeries(activity.data?.summary.volumeSeries ?? [], range.value)} format={nairaCompact} />
          )}
          <div className="mt-4 max-w-xs">
            <SelectField
              label="Reporting period"
              value={period}
              onChange={setPeriod}
              options={PERIODS.map((value) => ({ value, label: value }))}
              hint="Applies to the documents you generate below."
            />
          </div>
        </Panel>

        <Panel title="Documents" description="Generated monthly and kept for seven years.">
          {reports.isLoading ? (
            <LoadingPanel />
          ) : reports.isError ? (
            <ErrorState onRetry={() => void reports.refetch()} />
          ) : (reports.data ?? []).length === 0 ? (
            <EmptyState
              title="No reports yet"
              body="Your first report is generated after your first full payroll cycle."
              icon={<FileText className="h-5 w-5" />}
            />
          ) : (
            <ul className="space-y-2.5">
              {(reports.data ?? []).map((statement) => (
                <li
                  key={statement.id}
                  className="flex items-center gap-3.5 rounded-2xl border border-border p-4"
                >
                  <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-muted-foreground">
                    <FileText className="h-4 w-4" />
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="block truncate text-sm font-semibold text-foreground">
                      {statement.title}
                    </span>
                    <span className="mt-0.5 block text-xs text-muted-foreground">
                      {statement.period} · {statement.sizeKb} KB
                    </span>
                  </span>
                  <ActionButton
                    size="sm"
                    variant="secondary"
                    loading={downloading === statement.id}
                    onClick={() => void download(statement)}
                  >
                    Download
                  </ActionButton>
                </li>
              ))}
            </ul>
          )}
          <InfoNote className="mt-4">
            Reports contain payroll figures only — never an employee's reasons or personal spending.
          </InfoNote>
        </Panel>
      </div>
    </div>
  );
}
