import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, FileText } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, ActionButton } from "@/components/dashboard/PageHeader";
import { Panel, SummaryRow, InfoNote } from "@/components/dashboard/Panel";
import { StatCard, StatGrid } from "@/components/dashboard/StatCard";
import { EmptyState, ErrorState, LoadingPanel } from "@/components/dashboard/states";
import { SelectField } from "@/components/dashboard/forms";
import { TrendChart, BarSeries, DonutSplit, ChartTabs, useChartRange, sliceSeries } from "@/components/dashboard/charts";
import { opsApi, qk } from "@/lib/platform/mock-service";
import { downloadCsv, downloadFile, naira, nairaCompact, shortDate } from "@/lib/platform/format";
import type { Statement } from "@/lib/platform/models";

const REPORTS = [
  { title: "Platform activity report", detail: "Bridge volume, values and settlement performance" },
  { title: "Capital and funding report", detail: "Deployment, exposure and repayment behaviour" },
  { title: "Employer exposure report", detail: "Limits, utilisation and payroll obligations" },
  { title: "Regulatory summary", detail: "KYC, KYB, screening and case outcomes" },
];

export default function OperationsReportsPage() {
  const range = useChartRange(["3M", "6M", "12M"] as const);
  const [view, setView] = useState("Volume");
  const [period, setPeriod] = useState("This month");
  const [downloading, setDownloading] = useState<string | null>(null);

  const overview = useQuery({ queryKey: qk.ops("overview"), queryFn: () => opsApi.overview() });
  const statements = useQuery({ queryKey: qk.ops("reports"), queryFn: () => opsApi.reports() });
  const transactions = useQuery({ queryKey: qk.ops("transactions"), queryFn: () => opsApi.transactions() });

  const series = sliceSeries(overview.data?.volume ?? [], range.value);

  const download = async (title: string, period_: string) => {
    setDownloading(title);
    await new Promise((resolve) => setTimeout(resolve, 900));
    downloadFile(
      `${title.replace(/\s+/g, "-").toLowerCase()}.txt`,
      [
        "PayBridge — Internal report",
        `Report: ${title}`,
        `Period: ${period_}`,
        `Generated: ${shortDate(new Date().toISOString())}`,
        "",
        `Bridge value today: ${naira(overview.data?.bridgeValueToday ?? 0)}`,
        `Capital deployed: ${naira(overview.data?.deployedCapital ?? 0)}`,
        `Available capital: ${naira(overview.data?.availableCapital ?? 0)}`,
        `Salary Buffer exposure: ${naira(overview.data?.salaryBufferExposure ?? 0)}`,
        `Repayments due: ${naira(overview.data?.repaymentsDue ?? 0)}`,
        "",
        "Internal document. Generated by the PayBridge prototype.",
      ].join("\n"),
    );
    setDownloading(null);
    toast.success(`${title} downloaded`);
  };

  const exportLedger = () => {
    const data = (transactions.data ?? []).map((row) => ({
      Reference: row.reference,
      Type: row.type,
      Counterparty: row.counterparty,
      Employer: row.employerName ?? "",
      Amount: row.amount,
      Fee: row.fee,
      Date: shortDate(row.createdAt),
      Status: row.status,
      Reconciliation: row.reconciliation,
    }));
    if (!data.length) {
      toast.info("There is nothing to export in this period");
      return;
    }
    downloadCsv("paybridge-platform-ledger.csv", data);
    toast.success("Platform ledger exported");
  };

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Reports"
        title="Platform reporting"
        description="Activity, capital and regulatory reporting across every portal."
        actions={
          <ActionButton icon={<Download className="h-4 w-4" />} onClick={exportLedger}>
            Export ledger
          </ActionButton>
        }
      />

      <StatGrid columns={4}>
        <StatCard
          label="Bridge value today"
          value={naira(overview.data?.bridgeValueToday ?? 0)}
          hint={`${overview.data?.bridgeTransactionsToday ?? 0} transactions`}
          tone="primary"
        />
        <StatCard label="Capital deployed" value={nairaCompact(overview.data?.deployedCapital ?? 0)} tone="protected" />
        <StatCard label="Buffer exposure" value={nairaCompact(overview.data?.salaryBufferExposure ?? 0)} />
        <StatCard
          label="Repayments due"
          value={nairaCompact(overview.data?.repaymentsDue ?? 0)}
          tone="attention"
        />
      </StatGrid>

      <Panel
        title="Platform volume"
        description="Value bridged month by month."
        action={
          <div className="flex flex-wrap items-center gap-2">
            <ChartTabs options={["Volume", "Bars"] as const} value={view} onChange={setView} />
            <ChartTabs options={range.options} value={range.value} onChange={range.setValue} />
          </div>
        }
      >
        {overview.isLoading ? (
          <LoadingPanel />
        ) : overview.isError ? (
          <ErrorState onRetry={() => void overview.refetch()} />
        ) : view === "Volume" ? (
          <TrendChart data={series} format={nairaCompact} height={280} />
        ) : (
          <BarSeries data={series} format={nairaCompact} height={280} tone="available" />
        )}
      </Panel>

      <div className="grid gap-6 lg:grid-cols-[1fr_1.3fr]">
        <Panel title="Capital allocation" description="Where capital is deployed today.">
          {overview.data ? (
            <DonutSplit
              slices={overview.data.capitalSplit}
              centerLabel="Under management"
              centerValue={nairaCompact(
                overview.data.capitalSplit.reduce((sum, slice) => sum + slice.value, 0),
              )}
              format={nairaCompact}
            />
          ) : (
            <LoadingPanel />
          )}
        </Panel>

        <Panel
          title="Generate a report"
          description="Downloads a simulated document for the selected period."
          action={
            <div className="w-44">
              <SelectField
                label=""
                value={period}
                onChange={setPeriod}
                options={["This month", "Last month", "This quarter", "Year to date"].map((value) => ({
                  value,
                  label: value,
                }))}
              />
            </div>
          }
        >
          <ul className="space-y-2.5">
            {REPORTS.map((report) => (
              <li key={report.title} className="flex items-center gap-3.5 rounded-2xl border border-border p-4">
                <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-muted-foreground">
                  <FileText className="h-4 w-4" />
                </span>
                <span className="min-w-0 flex-1">
                  <span className="block text-sm font-semibold text-foreground">{report.title}</span>
                  <span className="mt-0.5 block text-xs text-muted-foreground">{report.detail}</span>
                </span>
                <ActionButton
                  size="sm"
                  variant="secondary"
                  loading={downloading === report.title}
                  onClick={() => void download(report.title, period)}
                >
                  Generate
                </ActionButton>
              </li>
            ))}
          </ul>
        </Panel>
      </div>

      <Panel title="Filed documents" description="Statements and reports already generated on the platform.">
        {statements.isLoading ? (
          <LoadingPanel />
        ) : statements.isError ? (
          <ErrorState onRetry={() => void statements.refetch()} />
        ) : (statements.data ?? []).length === 0 ? (
          <EmptyState
            title="No filed documents yet"
            body="Generated reports are filed here with the period they cover."
            icon={<FileText className="h-5 w-5" />}
          />
        ) : (
          <ul className="space-y-2.5">
            {(statements.data ?? []).map((statement: Statement) => (
              <li key={statement.id} className="flex items-center gap-3.5 rounded-2xl border border-border p-4">
                <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-secondary text-muted-foreground">
                  <FileText className="h-4 w-4" />
                </span>
                <span className="min-w-0 flex-1">
                  <span className="block truncate text-sm font-semibold text-foreground">{statement.title}</span>
                  <span className="mt-0.5 block text-xs text-muted-foreground">
                    {statement.kind} · {statement.period} · {statement.sizeKb} KB
                  </span>
                </span>
                <ActionButton
                  size="sm"
                  variant="secondary"
                  loading={downloading === statement.title}
                  onClick={() => void download(statement.title, statement.period)}
                >
                  Download
                </ActionButton>
              </li>
            ))}
          </ul>
        )}
      </Panel>

      <Panel title="Reporting notes">
        <div className="divide-y divide-border/70">
          <SummaryRow label="Reporting period" value={period} />
          <SummaryRow label="Currency" value="Nigerian Naira (₦)" />
          <SummaryRow label="Prepared by" value="PayBridge operations" />
        </div>
        <InfoNote className="mt-4">
          Internal reports contain payroll and settlement figures only. Employee reasons for a request and
          personal spending activity are never included.
        </InfoNote>
      </Panel>
    </div>
  );
}
