import { S3Client, PutObjectCommand, DeleteObjectsCommand, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

/**
 * KYC document object storage.
 *
 * Backed by any S3-compatible bucket (AWS S3, Cloudflare R2, Backblaze B2).
 * `KYC_S3_ENDPOINT` / `KYC_S3_FORCE_PATH_STYLE` only need to be set for
 * non-AWS providers — see backend/.env.example.
 *
 * `storageKey` is generated by the caller (routes/auth.ts) and validated
 * there before it ever reaches this module: `<cuid>/<uuid>.<ext>`, never
 * client-supplied. This module trusts that invariant rather than
 * re-validating it.
 */

let client: S3Client | undefined;

function s3(): S3Client {
  if (client) return client;
  client = new S3Client({
    region: process.env.KYC_S3_REGION,
    endpoint: process.env.KYC_S3_ENDPOINT || undefined,
    forcePathStyle: process.env.KYC_S3_FORCE_PATH_STYLE === "true",
    credentials: {
      accessKeyId: process.env.KYC_S3_ACCESS_KEY_ID ?? "",
      secretAccessKey: process.env.KYC_S3_SECRET_ACCESS_KEY ?? "",
    },
  });
  return client;
}

function bucket(): string {
  const name = process.env.KYC_S3_BUCKET;
  if (!name) throw new Error("KYC_S3_BUCKET is not configured");
  return name;
}

export async function putKycObject(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
  await s3().send(
    new PutObjectCommand({
      Bucket: bucket(),
      Key: key,
      Body: bytes,
      ContentType: contentType,
      // Identity documents: no public ACL, no cache directives that would let
      // an intermediary cache the bytes.
      CacheControl: "no-store",
    }),
  );
}

/**
 * A short-lived, single-purpose URL to view one document's bytes directly from
 * the bucket — never proxied through our own process, and never a link that
 * outlives the reviewer's screen.
 *
 * WHY presigned rather than a permanent public URL: the bucket holds identity
 * documents. A URL that works forever, once it leaks into a browser history, a
 * proxy log or a support screenshot, is a permanent hole. A signature that
 * expires in minutes closes itself.
 */
export async function getKycObjectViewUrl(key: string, expiresInSeconds = 300): Promise<string> {
  return getSignedUrl(s3(), new GetObjectCommand({ Bucket: bucket(), Key: key }), {
    expiresIn: expiresInSeconds,
  });
}

/**
 * Delete document bytes for storage keys whose rows are going away.
 *
 * Failures are logged, never thrown — see the caller in routes/auth.ts for
 * why a file that cannot be deleted must not block the customer's upload.
 */
export async function deleteKycObjects(keys: string[]): Promise<void> {
  if (keys.length === 0) return;
  try {
    await s3().send(
      new DeleteObjectsCommand({
        Bucket: bucket(),
        Delete: { Objects: keys.map((Key) => ({ Key })), Quiet: true },
      }),
    );
  } catch (error) {
    console.error(
      JSON.stringify({
        type: "kyc.storage_delete_failed",
        at: new Date().toISOString(),
        message: error instanceof Error ? error.message : String(error),
      }),
    );
  }
}
